routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    });

    Route::controller(RoleController::class)->group(function (){
        Route::prefix('roles')->group(function (){
            Route::as('roles.')->group(function (){
                Route::get('/edit/{id}', 'edit')->name('edit')->middleware('hasPermission:admin,roles.edit');
                Route::get('/create', 'create')->name('create')->middleware('hasPermission:admin,roles.create');
                Route::get('/', 'index')->name('index')->middleware('hasPermission:admin,roles.index');
                Route::get('/{id}', 'show')->name('show')->middleware('hasPermission:admin,roles.show');
                Route::post('/', 'store')->name('store')->middleware('hasPermission:admin,roles.store');
                Route::put('/{id}', 'update')->name('update')->middleware('hasPermission:admin,roles.update');
                Route::delete('/{id}', 'destroy')->name('destroy')->middleware('hasPermission:admin,roles.destroy');
            });
        });
    });

    Route::controller(UserController::class)->group(function (){
        Route::prefix('users')->group(function (){
            Route::as('users.')->group(function (){
                Route::get('/create', 'create')->name('create')->middleware('hasPermission:admin,users.create');
                Route::get('/', 'index')->name('index')->middleware('hasPermission:admin,users.index', 'cache.response:100');
                Route::get('/{id}', 'show')->name('show')->middleware('hasPermission:admin,users.show', 'cache.response:5');
                Route::post('/', 'store')->name('store')->middleware('hasPermission:admin,users.store');
                Route::put('/{id}', 'update')->name('update')->middleware('hasPermission:admin,users.update');
                Route::get('/edit/{id}', 'edit')->name('edit')->middleware('hasPermission:admin,users.edit');
                Route::delete('/{id}', 'destroy')->name('destroy')->middleware('hasPermission:admin,users.destroy');
            });
        });
    });

    Route::controller(CategoryController::class)->group(function (){
        Route::prefix('categories')->group(function (){
            Route::as('categories.')->group(function (){
                Route::get('/all', 'getAll')->name('all')->middleware('hasPermission:admin,categories.index');
                Route::get('/create', 'create')->name('create')->middleware('hasPermission:admin,categories.create');
                Route::get('/', 'index')->name('index')->middleware('hasPermission:admin,categories.index');
                Route::get('/{id}', 'show')->name('show')->middleware('hasPermission:admin,categories.show');
                Route::post('/', 'store')->name('store')->middleware('hasPermission:admin,categories.store');
                Route::put('/{id}', 'update')->name('update')->middleware('hasPermission:admin,categories.update');
                Route::get('/edit/{id}', 'edit')->name('edit')->middleware('hasPermission:admin,categories.edit');
                Route::delete('/{id}', 'destroy')->name('destroy')->middleware('hasPermission:admin,categories.destroy');
            });
        });
    });

    Route::controller(ProductController::class)->group(function (){
        Route::prefix('products')->group(function (){
            Route::as('products.')->group(function (){
                Route::get('/create', 'create')->name('create')->middleware('hasPermission:admin,products.create');
                Route::get('/', 'index')->name('index')->middleware('hasPermission:admin,products.index');
                Route::get('/{id}', 'show')->name('show')->middleware('hasPermission:admin,products.show');
                Route::put('/{id}', 'update')->name('update')->middleware('hasPermission:admin,products.update');
                Route::get('/edit/{id}', 'edit')->name('edit')->middleware('hasPermission:admin,products.edit');
                Route::post('/', 'store')->name('store')->middleware('hasPermission:admin,products.store');
                Route::delete('/{id}', 'destroy')->name('destroy')->middleware('hasPermission:admin,products.destroy');
            });
        });
    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';
    protected $fillable = [
        'name',
        'category_id',
        'image',
        'user_id',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->Where('name', 'like', '%'.$name.'%') : null;
    }

    public function scopeWithPrice($query, $price)
    {
        return $price ? $query->Where('price', 'like', '%'.$price.'%') : null;
    }

    public function scopeWithCategory($query, $category)
    {
        return $category ? $query->whereHas('category', function (Builder $query) use ($category) {
            $query->where('name', 'like', '%'.$category.'%');
        }) : null;
    }

    public function getPathOfImageAttribute()
    {
        return asset('storage/images/'.$this->image);
    }

    public function getImagePathOriginAttribute()
    {
        return storage_path('app/public/images/'.$this->image);
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\products\ProductCollection;
use App\Http\Resources\products\ProductResource;
use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function getList(Request $request)
    {
        $products = $this->productService->search($request);
        $productCollection = new ProductCollection($products);
        return $this->getResourceResponse($productCollection);
    }

    public function get($id)
    {
        $product= $this->productService->findOrFail($id);
        $productResource = new ProductResource($product);
        return $this->getResourceResponse($productResource);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\products\StoreProductRequest;
use App\Http\Requests\products\UpdateProductRequest;
use App\Http\Resources\products\ProductResource;
use App\Services\ProductService;
use Illuminate\Contracts\Cache\Repository as Cache;

class ProductController extends Controller
{
    protected $productService;
    protected $cache;

    public function __construct(ProductService $productService, Cache $cache)
    {
        $this->productService = $productService;
        $this->cache = $cache;
    }

    public function index()
    {
        return view('products.index');
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $this->productService->update($request, $id);
        $product = $this->productService->find($id);
        $productResource = new ProductResource($product);
        return $this->getResourceResponse($productResource);
    }

    public function store(StoreProductRequest $request)
    {
        $product = $this->productService->create($request);
        $productResource = new ProductResource($product);
        return $this->getResourceResponse($productResource);
    }

    public function destroy($id)
    {
        $product = $this->productService->find($id);
        $this->productService->delete($id);
        $productResource = new ProductResource($product);
        return $this->getResourceResponse($productResource);
    }
}

resources/views/products/create.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 mx-auto">
                    <div class="card mt-4">
                        <div class="card-header p-3">
                            <h5 class="mb-0">Create Product</h5>
                        </div>
                        <div class="card-body p-3">
                            <form role="form" class="text-start" method="POST" id="formData" enctype="multipart/form-data" action="{{ route('products.store') }}">
                                <label class="form-label">Name</label>
                                <div class="input-group input-group-outline mt-3 mb-0">
                                  <input id="name" type="text" class="form-control" name="name">
                                </div>
                                <span class="text-sm text-danger d-block name"></span>
                                <label class="form-label">Category</label>
                                <div class="input-group input-group-outline mt-3 mb-0">
                                    <select name="category_id" class="form-control" id="exampleFormControlSelect1">
                                        <option value="">Choose Category</option>
                                        @foreach ($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <span class="text-sm text-danger d-block category_id"></span>
                                <label class="form-label">Price</label>
                                <div class="input-group input-group-outline mt-3 mb-0">
                                  <input id="price" type="text" class="form-control" name="price">
                                </div>
                                <span class="text-sm text-danger d-block price"></span>
                                <label class="form-label">Image</label>
                                <div class="input-group input-group-outline mt-3 mb-0">
                                  <input id="image" type="file" class="form-control" name="image">
                                </div>
                                <span class="text-sm text-danger d-block image"></span>
                                <div class="row">
                                    <div class="col-lg-3 col-sm-6 col-12 mt-sm-0 mt-2">
                                      <button id="btn-create" class="btn bg-gradient-info mb-0 toast-btn" type="button" data-target="infoToast">Create</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
        </div>
    </div>
    </div>
</div>

resources/views/products/edit.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 mx-auto">
                    <div class="card mt-4">
                        <div class="card-header p-3">
                            <h5 class="mb-0">Update Product</h5>
                        </div>
                        <div class="card-body p-3">
                            <form role="form" class="text-start" method="POST" id="formData" enctype="multipart/form-data" action="{{ route('products.update', $product->id) }}">
                                <label class="form-label">Name</label>
                                <div class="input-group input-group-outline mt-3">
                                  <input id="name" type="text" class="form-control" name="name" value="{{$product->name}}">
                                </div>
                                <span class="text-sm text-danger d-block name"></span>
                                <label class="form-label">Category</label>
                                <div class="input-group input-group-outline mt-3">
                                    <select name="category_id" class="form-control" id="exampleFormControlSelect1">
                                        @foreach ($categories as $category)
                                            <option value="{{$category->id}}" @if($product->category->id == $category->id) selected @endif>{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <label class="form-label">Price</label>
                                <div class="input-group input-group-outline mt-3">
                                  <input id="price" type="text" class="form-control" name="price" value="{{$product->price}}">
                                </div>
                                <span class="text-sm text-danger d-block price"></span>
                                <label class="form-label">Image</label>
                                <div class="input-group input-group-outline mt-3">
                                    <img src="{{$product->path_of_image}}" alt="image of this product">
                                </div>
                                <div id="image-update">
                                    <label class="form-label">Update Image</label>
                                    <div class="input-group input-group-outline mt-3">
                                        <input id="image" type="file" class="form-control" name="image">
                                        <input type="hidden" name="_method" value="PUT">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-3 col-sm-6 col-12 mt-sm-0 mt-2">
                                      <button id="btn-update" class="btn bg-gradient-info mb-0 toast-btn" type="button" data-target="infoToast">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
        </div>
    </div>
    </div>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <a type="button" class="btn bg-gradient-info toast-btn" @unlesshasPermission('admin', 'products.create') invisible @endhasPermission data-target="infoToast" id="create-product" data-action="{{route('products.store')}}" data-type="create">Create +</a>
                <form role="form" class="text-start" action="{{route('api-products.list')}}" id="formSearch">
                    <input class="search-product" type="text" name="name" placeholder="Name" data-link="{{ route('products.index') }}">
                    <input class="search-product" type="text" name="price" placeholder="Price" data-link="{{ route('products.index') }}">
                    <input class="search-product" type="text" name="category" placeholder="Category" data-link="{{ route('products.index') }}">
                </form>
            </div>
            <div>
                <div class="card my-4">
                    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                            <h6 class="text-white text-capitalize ps-3">Products table</h6>
                        </div>
                    </div>
                    <div class="card-body px-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                    <tr>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            No</th>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            Name</th>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            Category</th>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            Price</th>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            Image</th>
                                        <th
                                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            Action</th>
                                    </tr>
                                </thead>
                                <tbody id="data-product">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div id="pagination">
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="product-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 mx-auto">
                            <div class="card mt-4">
                                <div class="card-header p-3">
                                    <h5 class="mb-0" id="modal-title"></h5>
                                </div>
                                <div class="card-body p-3">
                                    <form role="form" class="text-start" method="POST" id="formData" enctype="multipart/form-data">
                                        <label class="form-label">Name</label>
                                        <div class="input-group input-group-outline mt-3 mb-0">
                                            <input id="name" type="text" class="form-control" name="name">
                                        </div>
                                        <span class="text-sm text-danger d-block name"></span>
                                        <label class="form-label">Category</label>
                                        <div class="input-group input-group-outline mt-3 mb-0">
                                            <select name="category_id" class="form-control" id="categories" data-api="{{route('api-categories.all')}}">
                                            </select>
                                        </div>
                                        <span class="text-sm text-danger d-block category_id"></span>
                                        <label class="form-label">Price</label>
                                        <div class="input-group input-group-outline mt-3 mb-0">
                                            <input id="price" type="text" class="form-control" name="price">
                                        </div>
                                        <span class="text-sm text-danger d-block price"></span>
                                        <div id="show-image">
                                        </div>
                                        <div id="add-image">
                                        </div>
                                        <span class="text-sm text-danger d-block image"></span>
                                        <div class="row" id="product-submit">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
@endsection
@section('footer')
<script type="module" src="{{asset('assets/js/products/product.js')}}"></script>
@endsection

resources/views/products/list.blade.php
<div class="card my-4">
    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Products table</h6>
        </div>
    </div>
    <div class="card-body px-0 pb-2">
        <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
                <thead>
                    <tr>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            No</th>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            Name</th>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            Category</th>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            Price</th>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            Image</th>
                        <th
                            class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                            Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1 justify-content-center">
                                    <h6 class="mb-0 text-sm">{{$loop->iteration}}</h6>
                                </div>
                            </td>
                            <td class="text-center">
                                <p class="text-xs font-weight-bold mb-0">
                                    <a @hasPermission('admin|user', 'products.show') data-api="{{route('api-products.get', $product->id)}}" type="button" class="show-product" @endhasPermission data-type="show">
                                        {{$product->name}}
                                    </a>
                                </p>
                            </td>
                            <td class="text-center">
                                <p class="text-xs font-weight-bold mb-0">
                                    {{$product->category->name}}
                                </p>
                            </td>
                            <td class="text-center">
                                <p class="text-xs font-weight-bold mb-0">
                                    {{$product->price}}
                                </p>
                            </td>
                            <td class="text-center">
                                <p class="text-xs font-weight-bold mb-0">
                                    {{$product->image}}
                                </p>
                            </td>
                            <td class="align-middle text-center">
                                @hasPermission('admin|user', 'products.edit')
                                    <a data-api="{{route('api-products.get', $product->id)}}" data-action="{{route('products.update', $product->id)}}" data-type="edit" class="text-secondary font-weight-bold text-xs edit-product" type="button">
                                        Edit
                                    </a>
                                @endhasPermission
                                <span>|</span>
                                @hasPermission('admin|user', 'products.destroy')
                                    <button type="button" class="text-secondary font-weight-bold text-xs border-0 btn-delete" style="background:none"
                                    data-toggle="tooltip" data-original-title="Delete" data-action="{{route('products.destroy', $product->id)}}">Delete</button>
                                @endhasPermission
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
{{$products->links()}}

resources/views/products/show.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-modal">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 mx-auto">
                    <div class="card mt-4">
                        <div class="card-header p-3">
                            <h5 class="mb-0">Show Product</h5>
                        </div>
                        <div class="card-body p-3 pb-0">
                            <label class="form-label">Name</label>
                            <div class="input-group input-group-outline my-3">
                                <input disabled type="text" class="form-control" value="{{$product->name}}">
                            </div>
                            <label class="form-label">Category</label>
                            <div class="input-group input-group-outline my-3">
                                <input disabled type="text" class="form-control" value="{{$product->category->name}}">
                            </div>
                            <label class="form-label">Price</label>
                            <div class="input-group input-group-outline mt-3">
                            <input id="price" type="text" class="form-control" name="price" value="{{$product->price}}">
                            </div>
                            <label class="form-label">Image</label>
                            <div class="input-group input-group-outline mt-3">
                                <img src="{{$product->path_of_image}}" alt="image of this product">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
        </div>
    </div>
    </div>
</div>